### ISSUE TITLE
Unable to find in MacForge?

### ISSUE THREAD

**Issue by wdhwg001** [MacEnhance/Goodbye#3]
Hi,

I just noticed that the link in readme.md will be redirected to the homepage of MacForge, and Goodbye is not found in MacForge's search.

Is there a manual way to install this plugin?

Thanks!

**Comment by w0lfschild** [comment]
Currently you'd have to build it yourself until I publish it.

**Comment by geochronology** [comment]
How does one built it oneself? (New to mac dev environment)

**Comment by w0lfschild** [comment]
@geochronology 

Download the project
Open it with Xcode
Click the little `▶️` icon in the top left corner of Xcode to build

Might be worth looking up on Youtube or something if you're actually interested in going deeper than clicking a button.
